// RANKING
export const MOVIELIST_RANKING = 'MOVIELIST_RANKING';

// Today
export const MOVIELIST_TODAY = 'MOVIELIST_TODAY';

// THIS WEEK
export const REQUEST_MOVIELIST_THISWEEK = 'REQUEST_MOVIELIST_THISWEEK';
export const MOVIELIST_THISWEEK = 'MOVIELIST_THISWEEK';

// RECENT MOVIE
export const MOVIELIST_RECENT_MOVIE = 'MOVIELIST_RECENT_MOVIE';

// THEATER
export const REQUEST_THEATER = 'REQUEST_THEATER';
export const MOVIELIST_THEATER = 'MOVIELIST_THEATER';
export const REQUEST_MOVIELIST_THEATER_TIME = 'REQUEST_MOVIELIST_THEATER_TIME';
export const MOVIELIST_THEATER_TIME = 'MOVIELIST_THEATER_TIME';

// More
export const BUY_TICKETS_LINKING = 'BUY_TICKETS_LINKING';
export const SEND_SEARCH_FORM = 'SEND_SEARCH_FORM';
export const DEFAULT_SEND_SEARCH_FORM = 'DEFAULT_SEND_SEARCH_FORM';
export const SEARCH_TIME_REQUEST = 'SEARCH_TIME_REQUEST';
export const SEARCH_TIME = 'SEARCH_TIME';

// Movie Detail
export const REQUEST_MOVIE_DETAIL = 'REQUEST_MOVIE_DETAIL';
export const MOVIE_DETAIL = 'MOVIE_DETAIL';
