// RANKING
export const MOVIELIST_RANKING = 'MOVIELIST_RANKING';
// THIS WEEK
export const REQUEST_MOVIELIST_THISWEEK = 'REQUEST_MOVIELIST_THISWEEK';
export const MOVIELIST_THISWEEK = 'MOVIELIST_THISWEEK';
