// RANKING
export const MOVIELIST_RANKING = 'MOVIELIST_RANKING';
// Today
export const MOVIELIST_TODAY = 'MOVIELIST_TODAY';
// THIS WEEK
export const REQUEST_MOVIELIST_THISWEEK = 'REQUEST_MOVIELIST_THISWEEK';
export const MOVIELIST_THISWEEK = 'MOVIELIST_THISWEEK';
// RECENT MOVIE
export const MOVIELIST_RECENT_MOVIE = 'MOVIELIST_RECENT_MOVIE';
// THEATER
export const MOVIELIST_THEATER = 'MOVIELIST_THEATER';
